# Generated by Django 4.2.5 on 2023-11-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clube',
            new_name='Record',
        ),
    ]
