# Generated by Django 4.2.5 on 2023-11-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id_club', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id_player', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('current_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('destiny_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny_transfer', to='webapp.club')),
                ('origin_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_transfer', to='webapp.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.player')),
            ],
        ),
    ]
