# Generated by Django 4.2.5 on 2023-11-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('clube_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfersapp.clube')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('data_transferencia', models.DateField()),
                ('clube_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='transfersapp.clube')),
                ('clube_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem', to='transfersapp.clube')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfersapp.jogador')),
            ],
        ),
    ]
