# Generated by Django 4.2.5 on 2023-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_transfer_destiny_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_club',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='player',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
