# Generated by Django 4.2.5 on 2023-11-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_player_current_club_alter_transfer_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
